// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoru0IMUsdROu-wJRwne6qKXJyAWfMtQY',
    appId: '1:582879525679:web:55af91350e7daacd77bfda',
    messagingSenderId: '582879525679',
    projectId: 'contacts-fire-529ed',
    authDomain: 'contacts-fire-529ed.firebaseapp.com',
    storageBucket: 'contacts-fire-529ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZcbshjZ7Q4IF0mmVvtVmypEToE4yEid0',
    appId: '1:582879525679:android:ca60c83d4dbd518a77bfda',
    messagingSenderId: '582879525679',
    projectId: 'contacts-fire-529ed',
    storageBucket: 'contacts-fire-529ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnRPwWgGz6Sp4rrykqkS7xGYOM0Tf1Kpo',
    appId: '1:582879525679:ios:47cae2951082f06277bfda',
    messagingSenderId: '582879525679',
    projectId: 'contacts-fire-529ed',
    storageBucket: 'contacts-fire-529ed.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnRPwWgGz6Sp4rrykqkS7xGYOM0Tf1Kpo',
    appId: '1:582879525679:ios:03cf7870430d854277bfda',
    messagingSenderId: '582879525679',
    projectId: 'contacts-fire-529ed',
    storageBucket: 'contacts-fire-529ed.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
